name: Release Build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: depsaw-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: depsaw-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: depsaw-macos-amd64
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare binary
        if: matrix.os != 'windows-latest'
        run: |
          cp target/${{ matrix.target }}/release/depsaw ${{ matrix.asset_name }}
          chmod +x ${{ matrix.asset_name }}

      - name: Prepare binary (Windows)
        if: matrix.os == 'windows-latest'
        run: copy target\${{ matrix.target }}\release\depsaw.exe ${{ matrix.asset_name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ matrix.asset_name }}
